### ISSUE TITLE
Bad grunt dependency

### ISSUE THREAD

**Issue by fruestueck** [geedew/grunt-yamllint#1]
Hello Everyone!

First of all, i'm not that experienced in linux. So please excuse me if i am wrong somewhere.
Second, nice job with yamllint : )

Now to my Problem: I am about to setup a [magicmirror](https://github.com/MichMich/MagicMirror) with an raspberry pi 3 and so far everything works great. As a last tuning i would like to install an magicmirror module [www-wienerlinien](https://github.com/fewieden/MMM-WienerLinien) to get some informations of the public transportation in my area.
The Git Module requires an npm installtion of "request". Every time i try to get that one to work i recive an UNMET PEER DEPENDENCY Error grunt@1.0.1
After some research i figured out that grunt-yamllint is somehow using a bad dependency request of grunt@0.4.0 wich is outdated (i think).

So, i asked myself, where the Error comes from. From yamllint, or from request or is it just that i a m to much of a newby to get it done? Would be gratful for any advide what to do next.
Please excuse me, if i should't write you in the first place. I just tryed to followed the Error to its root and i am still not sure if it is yamillint or something else i did't think of.

I am happy looking forwart to hear from you.

Best Regards,
Frühstück

**Comment by geedew** [comment]
I haven't made an update to this in a while. I will get it working with latest and let you know. 

Thanks,

Drew
@geedew

**Comment by geedew** [comment]
I went ahead and updated all of the dependencies. Tests pass and work fine. #2

**Comment by fruestueck** [comment]
EDIT: Don't know if your work helped. But i found my mistake. An missing "}" in the config file. As an programmer i know how common and also ideotic this kind of mistake is^^
Still, thank you very much!

**Comment by geedew** [comment]
Happens to all of us! To be clear, it was broken and @jonnor pointed out the fix. The newest version should work great.
