### ISSUE TITLE
Feature Request: Exclude Option

### ISSUE THREAD

**Issue by simlu** [geedew/grunt-yamllint#3]
Would be great to be able to exclude certain directories, e.g. node_modules

**Comment by prantlf** [comment]
You can put the exclusion pattern among the other (inclusion) file patterns. You prefix it with the exclamation mark. For example, how to include everything in "files" recursively, but exclude anything in "files/excluded":

```json
   ["files/**/*.yml", "!files/excluded/**/*.yml"]
```

See [Grunt file globbing patterns](https://gruntjs.com/configuring-tasks#globbing-patterns) for more information.

I see no need for an explicit `exclude` option. It would not fit to the concept of [specifying file patterns in Grunt](https://gruntjs.com/configuring-tasks#files). How about closing this issue?

**Comment by simlu** [comment]
Thanks for the reply!

Have totally moved away from grunt for all my (open source) packages since writing this, so closing.
